package com.mp3song.playmusic.helpers.avsbb;

// Custom exception for invalid inputs.
public class InvalidInputException extends Exception {
    // Serial version ID generated by Eclipse.
    private static final long serialVersionUID = -2505698991597837165L;

    public InvalidInputException(String message) {
        super(message);
    }
}